options:
  # logging: "NONE"
  logging: "gs://nextjs-website-logbucket"
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nextjs-website:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nextjs-website:$COMMIT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/nextjs-website:$COMMIT_SHA'
