options:
  # logging: "NONE"
  logging: CLOUD_LOGGING_ONLY # Use CLOUD_LOGGING_ONLY for Cloud Logging or CLOUD_LOGGING_AND_STORAGE to store logs in GCS
steps:
  - name: "node:alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        npm install
        npm run build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/nextjs-website:$COMMIT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/nextjs-website:$COMMIT_SHA",
      ]

images:
  - "$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/nextjs-website:$COMMIT_SHA"

substitutions:
  _LOCATION: "us"
  _REPOSITORY: "containers"
