---
apiVersion: v1
kind: Pod
metadata:
  name: nextjs-website-pod
  namespace: test-ns
  labels:
    app: nextjs-website
spec:
  imagePullSecrets:
    - name: my-registry-secret  # The name of your image pull secret
  containers:
  - name: nextjs-website
    image: nextjs-website:latest  # This is your Docker image
    ports:
    - containerPort: 3000
