"use client";

import React from "react";
import ShieldIcon from "./svg/ShieldIcon";
import LockIcon from "./svg/LockIcon";
import "../styles/landing.css";

export default function LandingPageContent() {
  return (
    <div className="landing-page">
      {/* Hero Section */}
      <section className="landing-hero">
        <div className="landing-hero__scan" />
        <ShieldIcon className="landing-hero__shield" />
        <h1 className="landing-hero__headline">
          Your Site Is <span>Protected</span>
        </h1>
        <p className="landing-hero__subtitle">
          Advanced bot detection and human verification keeping this site safe
          from automated threats.
        </p>
        <div className="landing-hero__terminal">
          <span>$ status: all systems secured</span>
          <span className="landing-hero__terminal-cursor" />
        </div>
      </section>

      {/* What Is Bot Protection */}
      <section className="landing-section">
        <h2 className="landing-section__title">
          What Is <span>Bot Protection</span>?
        </h2>
        <div className="landing-cards">
          <div className="landing-card">
            <LockIcon className="landing-card__icon" />
            <h3 className="landing-card__title">Bot Detection</h3>
            <p className="landing-card__text">
              Behavioral analysis and fingerprinting distinguish real users from
              automated scripts, blocking malicious bots before they can act.
            </p>
          </div>
          <div className="landing-card">
            <LockIcon className="landing-card__icon" />
            <h3 className="landing-card__title">Human Verification</h3>
            <p className="landing-card__text">
              Invisible challenges verify legitimate visitors without disrupting
              the user experience, keeping friction low and security high.
            </p>
          </div>
          <div className="landing-card">
            <LockIcon className="landing-card__icon" />
            <h3 className="landing-card__title">Threat Intelligence</h3>
            <p className="landing-card__text">
              Real-time threat data from global networks identifies known attack
              patterns and emerging threats before they reach your application.
            </p>
          </div>
        </div>
      </section>

      {/* Why It Matters */}
      <section className="landing-section">
        <h2 className="landing-section__title">
          Why It <span>Matters</span>
        </h2>
        <div className="landing-stats">
          <div className="landing-stat">
            <div className="landing-stat__number">40%+</div>
            <div className="landing-stat__label">
              Of all internet traffic is generated by bots, many of them
              malicious.
            </div>
          </div>
          <div className="landing-stat">
            <div className="landing-stat__number">$6T</div>
            <div className="landing-stat__label">
              Annual cost of cybercrime globally, with credential stuffing and
              account takeover on the rise.
            </div>
          </div>
          <div className="landing-stat">
            <div className="landing-stat__number">95%</div>
            <div className="landing-stat__label">
              Of credential stuffing attacks use automated bots to test stolen
              credentials at scale.
            </div>
          </div>
        </div>
      </section>

      {/* How This Site Is Protected */}
      <section className="landing-section">
        <h2 className="landing-section__title">
          How This Site Is <span>Protected</span>
        </h2>
        <div className="landing-steps">
          <div className="landing-step">
            <div className="landing-step__number">1</div>
            <h3 className="landing-step__title">PerimeterX Integration</h3>
            <p className="landing-step__text">
              Client-side sensors collect behavioral signals and device
              fingerprints on every page load.
            </p>
          </div>
          <div className="landing-step">
            <div className="landing-step__number">2</div>
            <h3 className="landing-step__title">Risk Scoring</h3>
            <p className="landing-step__text">
              Machine learning models analyze collected data in real time to
              produce a risk score for each visitor.
            </p>
          </div>
          <div className="landing-step">
            <div className="landing-step__number">3</div>
            <h3 className="landing-step__title">Challenge or Allow</h3>
            <p className="landing-step__text">
              Low-risk visitors pass through seamlessly. Suspicious traffic
              receives an invisible challenge or is blocked.
            </p>
          </div>
          <div className="landing-step">
            <div className="landing-step__number">4</div>
            <h3 className="landing-step__title">Continuous Monitoring</h3>
            <p className="landing-step__text">
              Ongoing session analysis detects anomalies and adapts defenses as
              threat patterns evolve.
            </p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <p className="landing-footer__text">
          <span>bhenning.com</span> &mdash; secured and monitored
        </p>
      </footer>
    </div>
  );
}
